apiVersion: v1
kind: Secret
metadata:
  name: db-admin
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  user: {{ .Values.dbAdmin.user | quote }}
  password: {{ .Values.dbAdmin.password | quote }}
