{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-password
stringData:
  username: {{ .Values.username | quote }}
  password: {{ .Values.password | quote }}
{{- end }}
